---
title: "Projet de cours"
subtitle: "MTH8211"
author:
  - name: Wadih Chalhoub
  - name: Nicolas Alacoque
    email: wadih.chalhoub@polymtl.ca
    affiliation:
      - name: Polytechnique Montréal
format:
  pdf:
    keep-tex: false
    documentclass: article
    include-in-header:
      - text: |
            \usepackage{xspace}
            \usepackage[francais]{babel}
    geometry:
      - margin=1in
    papersize: letter
    colorlinks: true
    urlcolor: blue
engine: julia
---

# Contexte et Motivations  
Les techniques de visualisation d’espaces occupent une place centrale dans des domaines variés, allant de l’art numérique aux jeux vidéo, en passant par des applications scientifiques comme la discrétisation de volumes pour les simulations numériques. Ces méthodes permettent de transformer des représentations 2D, telles que des images ou des scans, en modèles 3D discrets, essentiels pour des analyses physiques ou médicales, notamment en imagerie médicale ou en simulations CFD.  
Le passage d’une image 2D à un espace 3D discrétisé repose sur des systèmes matriciels issus du traitement du signal, comme les équations aux dérivées partielles ou les problèmes de moindres carrés. Ces matrices présentent souvent des structures particulières, creuses ou bloc-diagonales, qui reflètent les contraintes physiques du problème.  
  
La résolution de ces systèmes linéaires de grande taille exige des méthodes numériques à la fois stables et efficaces. La décomposition QR se présente comme une solution privilégiée, surtout lorsque la structure creuse ou bloc peut être exploitée pour réduire la complexité calculatoire.  

## Objectif de l’Étude  

Cette étude compte élaborer les meilleurs implémentations 
Julia des stratégies de factorisation QR creuse pour des 
problèmes aux moindres carrés structurés en termes d'éfficacité 
et de capacités, notamment vis-à-vis des structures de matrices 
de types demandé ('bloc diagonale', 'concaténée horizontale' ainsi que, 
dans le mesure du possible dans le temps qui est accordé,   
'bloc-bande', et 'concatenée verticale') ainsi que la 
factorisation QR dense (LAPACK de Julia et Householder) et creuse 
(SuiteSparseQR de Julia) pour le traitement des blocs 
élémentaires.


# Construction de la Matrice

## Problèmes d'Ajustement de Faisceau

Les problèmes d'ajustement de faisceau sont des problèmes d'optimisation non linéaire ou on cherche à minimiser la somme des erreurs de reprojection :

$$
\min_{\{P_j\}, \{X_i\}} \sum_{i,j} \| \pi(P_j, X_i) - x_{ij} \|^2
$$

où :

- **$X_i$** : Position du $i$-ème point 3D (dans l'espace monde)  
- **$P_j$** : Paramètres de la $j$-ème caméra (matrice de projection)  
- **$\pi(P_j, X_i)$** : Projection du point $X_i$ dans l'image de la caméra $j$  
- **$x_{ij}$** : Observation 2D du point $i$ dans l'image $j$ (coordonnées pixel)

## Structure du Problème

La matrice jacobienne du système présente une structure creuse caractéristique :
$$
J = \begin{bmatrix}
\frac{\partial r_{11}}{\partial P_1} & 0 & \frac{\partial r_{11}}{\partial X_1} & \frac{\partial r_{11}}{\partial X_2} & 0 \\
\frac{\partial r_{12}}{\partial P_1} & 0 & 0 & \frac{\partial r_{12}}{\partial X_2} & 0 \\
0 & \frac{\partial r_{22}}{\partial P_2} & 0 & \frac{\partial r_{22}}{\partial X_2} & \frac{\partial r_{22}}{\partial X_3} \\
0 & \frac{\partial r_{23}}{\partial P_2} & 0 & 0 & \frac{\partial r_{23}}{\partial X_3}
\end{bmatrix}
$$
**Équation 1** : Structure de la matrice jacobienne pour 2 caméras et 3 points 3D
Cette structure provient du fait qu'un point 3D $X_i$ n'est visible que par un sous-ensemble de caméras.

# Plan d'Action pour la Factorisation QR Structurée

## Recherche Préliminaire
L'étude débutera par une analyse des travaux existants, notamment les algorithmes QRKit et SuiteSparseQR, ainsi que des modèles d'ajustement de faisceau. Cette revue bibliographique permettra d'identifier les meilleures pratiques et les optimisations possibles.

## Collecte et Préparation des Données
Deux types de données seront utilisés : des matrices synthétiques présentant des structures bloc-diagonales et concaténées, ainsi que des problèmes réels issus de la bibliothèque BundleAdjustmentModels.jl. Ces données serviront de base pour les tests et les comparaisons.

## Optimisation des Performances
L'accent sera mis sur la parallélisation des blocs indépendants et sur une gestion optimale de la mémoire. Ces optimisations visent à améliorer l'efficacité des calculs pour les problèmes de grande taille.

## Validation et Benchmarks
Des tests rigoureux compareront les performances de l'implémentation proposée avec celles des solveurs existants, comme SuiteSparseQR. Les mesures porteront sur la précision des résultats et les temps d'exécution.

# Attentes

Il sera certainement difficile à découvrir une amélioration 
sur les implémentations fourni gratuitement en licence 
source ouvert inclus dans les librairies de julia, 
mais l'éxploration permettra de cibler les opérations clés 
qui demandent le plus d'allocation de mémoire vive, et 
d'isoler les stratégies qui sont les plus utiles pour les 
problèmes d’ajustement de faisceaux. Quant à l'éfficacité, le temps d'execution sera comparé, et les résultats dépenderont principalement de la taille de la matrice, de l'algorithme employé, la précision spécifié, la structure de la matrice et la préconditionnement.

# Références
::: {#refs}
:::
- family-names: "Chalhoub"
  given-names: "Wadih"
  orcid: "https://github.com/I-IVI-I/Factorisation-QR-creuse.git"
- family-names: "Allaire"
  given-names: "J.J."
  orcid: "https://orcid.org/0000-0003-0174-9868"
- family-names: "Teague"
  given-names: "Charles"
  orcid: "https://orcid.org/0000-0001-8715-9476"
- family-names: "Scheidegger"
  given-names: "Carlos"
  orcid: "https://orcid.org/0009-0006-9163-6136"
- family-names: "Xie"
  given-names: "Yihui"
  orcid: "https://orcid.org/0000-0003-0645-5666"
- family-names: "Dervieux"
  given-names: "Christophe"
  orcid: "https://orcid.org/0000-0003-4474-2498"
- family-names: "Woodhull"
  given-names: "Gordon"
  orcid: "https://orcid.org/0009-0005-1809-8936"
title: "Quarto"
version: 1.7
doi: 10.5281/zenodo.5960048
date-released: 2025-04-28
url: "https://github.com/quarto-dev/quarto-cli"



@article{10.1145/2049662.2049670,
  author = {Davis, Timothy A.},
  title = {Algorithm 915, SuiteSparseQR: Multifrontal multithreaded rank-revealing sparse QR factorization},
  year = {2011},
  journal = {ACM Trans. Math. Softw.},
  volume = {38},
  number = {1},
  articleno = {8},
  doi = {10.1145/2049662.2049670},
  url = {https://doi.org/10.1145/2049662.2049670},
  month = dec,
  publisher = {Association for Computing Machinery},
  address = {New York, NY, USA}
}

@techreport{G-2020-42,
  author = {Angla, Célestine and Bigeon, Jean and Orban, Dominique},
  title = {Modeling and solving bundle adjustment problems},
  year = {2020},
  month = aug,
  number = {G-2020-42},
  type = {Les Cahiers du GERAD},
  institution = {Groupe d'études et de recherche en analyse des décisions},
  address = {GERAD, Montréal QC H3T 2A7, Canada},
  url = {https://www.gerad.ca/en/papers/G-2020-42}
}

@article{DBLP:journals/corr/abs-1802-03773,
  author = {Jan Svoboda and Thomas J. Cashman and Andrew W. Fitzgibbon},
  title = {QRkit: Sparse, Composable QR Decompositions for Efficient and Stable Solutions to Problems in Computer Vision},
  journal = {CoRR},
  volume = {abs/1802.03773},
  year = {2018},
  url = {http://arxiv.org/abs/1802.03773},
  eprinttype = {arXiv},
  eprint = {1802.03773}
}

